### ISSUE TITLE
KPI Tile 2.0 in Pagebook Error duplicate ID

### ISSUE THREAD

**Issue by MathiasSandhofer** [org-scn-design-studio-community/sdkpackage#121]
Hi all,

The error is reproducable with the following dashboard:
![kpitile2error2](https://cloud.githubusercontent.com/assets/19287823/15822019/92ff9ada-2bf3-11e6-8f19-7688f422ff62.PNG)

The error only occurs if the minichart of KPI Tile 2.0 is filled with points. E.g.:
x-Axis: ["0","25","50","75","100"]
y-Axis: ["20","30","20","30","10"]
![kpitile2error3](https://cloud.githubusercontent.com/assets/19287823/15822074/d62e709c-2bf3-11e6-8a4c-343d339dbbc9.PNG)

Then switch the page from page 0 to page 1 (e.g. by swiping) and back => the error appears in the console:
![kpitile2error1](https://cloud.githubusercontent.com/assets/19287823/15822081/ea1d6fea-2bf3-11e6-85b9-e7e8a1c26fd8.PNG)

Dashboard does not react anymore and no other components are drawn.
Note: the error does not appear without setting the minichart.

Can you provide a fix?

Thank you!
Best regards,
Mathias

**Comment by KarolKalisz** [comment]
I will need to check this, if you could export and attach the application this would help.

**Comment by MathiasSandhofer** [comment]
Sure. Here is the Dashboard:

[KPITILE_PAGEBOOK_ERROR-20160609100615.zip](https://github.com/org-scn-design-studio-community/sdkpackage/files/306400/KPITILE_PAGEBOOK_ERROR-20160609100615.zip)

As explained: Swipe left, swipe right => error
Thank you!

**Comment by MartinPankraz** [comment]
Hi Karol, hi Mathias,

I checked Mathias dashboard example. We have two options to overcome the duplicate id problem on component re-creation.

1) We have to come up with a destructor logic so that we can clean up the created objects. (code line 464 - sap.suite.ui.commons). Obviously they are not freed or at least the ids are still rememberd although the component was dropped from the canvas. I am not sure what the UI5 framwork does when we create UI5 objects like that.

2) Change the unique id creation mechanism. I replaced the nextKey iterator with math.random to test. That works like a charm but bears the risk keep unwanted UI5 objects.

@KarolKalisz Do you have any smart ideas on the destroy topic? Otherwise I will change the code like is suggested under 2) to fix this.

Kind regards
Martin

**Comment by MathiasSandhofer** [comment]
Hi Karol, hi Martin,

are there any news about the correction of this error?

Thank you,
Mathias

**Comment by MartinPankraz** [comment]
Hi Mathias,

I pushed my fix just now. So the next build will contain it. Karol and I will check if there is a better solution for the uniqueness constraint at a later point in time.

Kind regards
Martin

**Comment by MathiasSandhofer** [comment]
Hi Martin,

thank you, it works fine now.

Best regards,
Mathias

**Comment by MartinPankraz** [comment]
That is good to hear. Thanks for the feedback!
