### ISSUE TITLE
Fiori App Header 2.0 Subitems not working (Data Source)

### ISSUE THREAD

**Issue by mlr1** [org-scn-design-studio-community/sdkpackage#130]
We are using the Fiori App Header 2.0 component in a Design Studio Application. The component works fine as long no data source is added to the application. 

Implementation: I added the Fiori App Header 2.0 component to the application with a main item and one sub item. On the "On Item Select" event I jut put "APPLICATION.alert("TEST");" for test purpose. I run the application locally. As I click on the sub button the alert "TEST" pops up. So this works fine! But as soon as I add a Data Source to the application the sub button no longer works. 

(NOTE: This only happens on the sub button. The main button works fine with or without any data source.)

Am I making any mistakes in the configuration of the component?

Thank you in advance.

![fiori app header problem 1](https://cloud.githubusercontent.com/assets/20238815/16515931/2c8c8e80-3f75-11e6-8dcf-27365c6a8a82.png)

![fiori app header problem 2](https://cloud.githubusercontent.com/assets/20238815/16515940/37ca6c4a-3f75-11e6-9437-c5de4bc561b6.png)

![fiori app header problem 3](https://cloud.githubusercontent.com/assets/20238815/16515945/3c511f8e-3f75-11e6-8ceb-9a5ee2bbf35e.png)

**Comment by MartinPankraz** [comment]
Hi mlr1,

I just tested what you describe. On my end there is no problem. Could you please verify if you are using an up to date version of Design Studio and our SCN SDK repository? Please also note that Mike flagged this component as deprecated for the commons dashboard mode. Consider migrating your dashboard to UI5 m mode.

Kind regards
Martin

**Comment by entmike** [comment]
That's a strange issue that it only occurs when a data source is present...  I'm using the Fiori App Header in a productive dashboard that has multiple data sources and it is working fine.  (Both in 1.5, as well as after recently going to 1.6 SP1)  Out of curiosity, are you on 1.6 SP0?  We avoided this one because of some bugs with non-visible component bugs (Technical Components and Data Source) and I'm wondering if this is a factor for you?

Also, I'd highly suggest M mode in lieu of Commons mode if this is possible.

**Comment by mlr1** [comment]
Thank you for your help. Changing to m Mode solves the problem.

Kind regards
Mirjam
