### ISSUE TITLE
EMBEDDED FRAME 2.0 open issue after implement #113

### ISSUE THREAD

**Issue by sreenichinta** [org-scn-design-studio-community/sdkpackage#142]
Martin,

After implementation of #113 it open window instated of embedded in current iframe. 

there are 2 scenarios 
1> if access home page from launch pad it works as embedded current report.
2> if i open through document link it is not working as expected

Thanks,
Sreeni

**Comment by MartinPankraz** [comment]
Hi Sreeni,

I really cannot follow your description. Please be more detailed and use screenshots if possible. And please bear in mind that your problem is more likely to come from your IT setup and I cannot do anything about that.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,
By current version BOE XI 4.1 SP7 Patch 1
Layout of my Home page where i use EMBEDDEDFRAME SDK
![capture](https://cloud.githubusercontent.com/assets/20972340/17994986/2cc4d9a2-6b7b-11e6-8f42-55addcdac7ac.PNG)

And each button is a new report which has to embedded in to home page (functionality looks like portal), 
We call this Home Page has document link in one of my SAP Portal system as open new window.

issue: 
Functionality working as expected if i access home page from BO launch pad.
It is not working if i access from Portal or through document link of home page.

Observations: 
1>if i add "&noDetailsPanel=true" to home page document link is working as expected since we have session time out issue (which needs to apply SAP Note:2268092) & it takes time to apply patch 4
2>if i don't add "&noDetailsPanel=true" to home page document link it open home page & if i select any of my button or report which has to embedded in to Home Page going off & open my report in same window.

i think you can understand the issue with this description.

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

Let me be clear about this. The only thing the SDK component does, is providing an iframe tag which is subject to browser security policies. If the target page does not behave as you expect it to, there is nothing we can do about it. From your short description it sounds like as if the BO server gets into trouble with session sharing. Once you click one of the buttons the Design Studio dashboard vanishes and the new url target uses the whole browser screen correct?

Maybe a workaround would be using APPLICATION.openNewWindow instead?

The only other thing I can think of is the sandbox attribute of the iframe tag which seperates the iframe more strictly from its parent container. But it is very likely that you can no longer use it fully then because several actions forbidden in the process. I might give it some more thought today.

Regarding oberservation 1, it is likely that once you apply the patch the session timeout is gone but you experience the same behavior as is in obeservation 2 afterwards.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,

Answers to questions:
1> Yes it is happening only if i don't add "&noDetailsPanel=true" before our new code deployment
this is not the case.
2>Should not open new window as per business requirement otherwise we don't need any SDK to open new window.
3> Yes please
4>Yes but i thought of calling document ink by adding "&noDetailsPanel=true"

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

I added the iframe sandbox attribute but it doesn't help your problem as I expected. The actual issue is with the Login procedure when embedding another BO page into a Design Studio application. The option "&noDetailsPanel" is not going to help in any case. It just appears so because it is a bug which is fixed by SAP now anyways.

You can test my suggestion to solve by logging in on the same browser on the BO app which will be the target of your button click for the embedded frame. This will create a session cookie for that app. Now if you run the Design Studio app with the embedded frame it will work as it should because the login process does not interfere. 

That being said, you need to work with your administrators on the login procedure to prevent the embedded frame target page from "overlapping" your design studio dashboard.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,
I need one more help, Do we have technical & functional documentation for EMBEDDED FRAME 2.0 component.

Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

No there is no additional component documentation. What you are actually asking is how to work with cross origin scenarios when embedding different web pages into one another. Only because our component allows to do that, that doesn't mean we can provide all missing information for you to customize your security settings and what makes your infrastructure tick.

Currently I am not able to help you with your pdf problem. You need to provide more details. Maybe attach at least a screenshot of the created pdf. My answers can only be as good as the input and research you provide yourself.

Kind regards
Martin

**Comment by sreenichinta** [comment]
Martin,
I requested you for maintaining purpose not to customize since this SDK component is moving to production coming soon.
I have attached pdf export which is missing embedded frame report in blank screen.
[Visibility Analytics_2.pdf](https://github.com/org-scn-design-studio-community/sdkpackage/files/463237/Visibility.Analytics_2.pdf)


Thanks,
Sreeni.

**Comment by MartinPankraz** [comment]
Hi Sreeni,

I can only offer to write up some more infos on the additional properties sheet "about" tab of the component. There is no official documentation that we release other than that.

Regarding the pdf I will try to have a look this afternoon.

Kind regards
Martin

**Comment by sreenichinta** [comment]
KarolKalisz,

Please help us.
Thanks,
Sreeni.
