### ISSUE TITLE
SAP Design Studio 1.6 SP4 patch 1 || SCN Extension Issues

### ISSUE THREAD

**Issue by lalohv** [org-scn-design-studio-community/sdkpackage#153]
Hello,

Recently we updated our dev server to SAP Design Studio 1.6 SP4 patch 1, also we updated the clients.

At first client launch, it pops up a window with a migration wizard for extensions (we already had installed SDK 3.0 stable version), after that, I made a test app using UI5 Table 2.0. When I added the component it doesn’t appear in the canvas but appear in the layout folder. After adding UI5 2.0 component I add more components but they doesn’t appear in canvas either, even if those components don’t belong to the extensions

![ds_1 6_sp4_pt1](https://cloud.githubusercontent.com/assets/25332986/22435290/11039574-e6e5-11e6-84c1-5a2d2092c44b.png)

Is there a programed update of SDK for 1.6 SP4 patch 1?

**Comment by MartinPankraz** [comment]
Hi Eduardo,

With SP4 the UI5 version must have been changed. The issue is with a method of the UI5 Table which has been renamed. The old one does not exist anymore so that the whole app crashes. I replaced it with the new one on our preview branch. You can update from here http://org-scn-design-studio-community.github.io/sdkinstall/releases/preview.

I am not sure how we deal with this on a global release level since we would like to support all SPs.

Let us know if you find any more glitches.

Kind regards
Martin

**Comment by KarolKalisz** [comment]
just installed SP4 to check. Thanks Martin for beeing quicker.
Btw. this change in UI5 is not making me happy... It means also that paginator is not available any more, right?

**Comment by MartinPankraz** [comment]
Yes, that is correct Karol. The property is deprecated. Only the scrollbar is allowed now.

**Comment by lalohv** [comment]
Thank you Martin, It was a quickly fix.

I just installed the update and it works, this help me a lot

Regards,
Eduardo
