### ISSUE TITLE
Design Studio SDK - Multi Combo Box - Not working with 1.6.4 patch 2

### ISSUE THREAD

**Issue by NickSinclair01** [org-scn-design-studio-community/sdkpackage#166]
Hello,

We are using the Multi Combo Box SDK component in Design Studio.

We recently upgraded our version to 1.6.4 patch 2. 

Since then the component only works if the tick box is used for selection, selecting the text/value no longer seems to commit the selection.

Any thoughts?

Thanks

Nick

**Comment by MartinPankraz** [comment]
Hi Nick,

Thanks for reaching out. Could you provide some more deatils please? What browser are you using? What dashboard mode (commons or m mode) do you have? Are you assigning the values through properties or the scripting method setItems?

Screenshots also help understanding things. An easy test application would be the most perfect contribution so that we can replicate easiest. You can create one by clicking export on DesignStudio. Make sure to isolate the problem to rule out any side effects.

Kind regards
Martin

**Comment by MartinPankraz** [comment]
The community’s implementation is only a wrapper for the standard sapui5 sap.m.MultiComboBox. So if SAP’s source is broken our implementation is also having problems.

The UI5 version shipped with DesignStudio 1.6 SP4 Patch 2 is 1.38.14. It seems this version has a bug regarding the sap.m.MultiComboBox in commons and m mode. Unfortunately the onSelectionFinished event fires before the onChange event if you click the text on the item list instead of the checkbox. If you stick to the checkbox only, you are fine. That is the behavior you experience. It is likely that the next Support Package or the upgrade to Lumira 2.0 will fix that issue with a newer UI5 version. Of course there is no guarantee to that.

For the time being I implemented a workaround so that you can continue with what you have. The change event is now firing on every selection directly because we cannot rely on the “finish” event. You will need to move your script to the change event because the other one is now hidden.

In case you don't want to trigger your script on any selection I would advise to add another "submit" button which fires your final selection eventually. This filter approach is very common in the Fiori world for example. So this would align with SAP's UX strategy.

Kind regards
Martin
