### ISSUE TITLE
addItems Method of SIDENAVIGATION component does not add items properly

### ISSUE THREAD

**Issue by MathiasSandhofer** [org-scn-design-studio-community/sdkpackage#180]
Hi experts,

we would like to implement the SIDENAVIGATION component of the SDK Community. Unfortunately the addItems Method does not work properly. 

**Error**: it is not possible to add submenu items to the nonfixed menu items by script.

I have attached an example dashboard for Design Studio 1.6 SP4. The scripting in the onStartup Script contains comments for the explanation of the error.

[SCN_SIDENAVIGATION_EXAMPLE-20171114131420.zip](https://github.com/org-scn-design-studio-community/sdkpackage/files/1470728/SCN_SIDENAVIGATION_EXAMPLE-20171114131420.zip)

Thank you for your effort!

Best regards,
Mathias

**Comment by MartinPankraz** [comment]
Hi Mathias,

The problem is withing the generated code base of the sidenavigation. I could fix but the next run of the generation would erase the fix again. However touching the big generation is no simple task. Karol and I decided to recreate the SideNavigation from scratch to avoid that. You can find the new and shiny implementation of the sidenavigation on my repository [now](http://martinpankraz.github.io/ConVista-DS-SDK-Visualizations/).

Kind regards
Martin

**Comment by MathiasSandhofer** [comment]
Hi Martin,

I tested your new component and it works marvellously.
Thank you!

Mathias
