### ISSUE TITLE
Preview and Stable ?

### ISSUE THREAD

**Issue by franckblais** [org-scn-design-studio-community/sdkpackage#29]
Hey !

I remember reading about creating a stable and preview version of the SDK package.
Should be have a branch only for that ?

For instance, I am upgrading the Hierarchical DropDown but It may still have a couple of bugs. I would merge it in the preview but not the stable.

**Comment by entmike** [comment]
It's pretty loose right now.  Karol and I don't really isolate them via branches but I'm open to the idea, it's just been pretty manageable to no bother with it right now.  Whatever I commit to the source code is usually "good enough" to show up in preview and stable so I've not been too worried.

If you have something that's kinda half-baked we can talk through a process to keep them from ending up in stable in this thread.  Karol may have some thoughts on a good approach, too.  I think he may be on a short vacation so when he returns let's see!

**Comment by franckblais** [comment]
Typically, I would like to commit sometimes, just to "save" my code etc.
Right know, I have 1 month of modification not committed yet ! (I don't have a lot of time ...).

Let's wait for Karol, but a "Preview" or "Sandbox" branch could be helpful, or at least I think so, even if is manageable like you said.

For people who wants to use the package, though, I think it would be clearer and easier to use.

**Comment by KarolKalisz** [comment]
we need some procedure here, for now really we do not have a real "production" work, but I assume we have to decide on this.

for today, and for me, I have following "rules":

BEFORE A COMPONENT IS READY
When I start new component (and the time spend per component is decreasing, so the time is not too long, perhaps one evening on basic stuff) then I check in first when I think it can be used. For backup, you can always check in the content and wait with the "script.cmd" and the central contributions - and check in first when the component is OK.

btw, to avoid merges, I always check if someone has checked in something in the meantime and reverting the generated files before I pull, then I regenerate.

AFTER A COMPONENT IS READY
this is the case for smaller improvement and fixes, and for now it is a rare case... then the time spend is basically short, so for me it can go directly to stable.

PROTOTYPES
when I want to make something just for fun, I make this in prototypes and there I hope noone will use it in real apps.

What is missing for me?
* some rules on "stable" version would be not bad, like once a 2 week-timeframe, or similar.
* we do not have a good "stable" history, means what is actually in.. I tried to start something, but it would require small investment to maintain and generate some HTML page.

Tricky point is, in order to separate good preview of stable, we would need to branch - and then the effort of work is higher. not saying this is not an idea for the future, but as of now I would not branch too much. but this could be at some point a solution, create a stable branch and push the code from master to stable - and then stable version would need to be an extra production step (currently we just copy the preview content).

Karol

**Comment by KarolKalisz** [comment]
as long we have no real business case for "release" and "preview" separation, I close this topic.
